### ISSUE TITLE
unhashable type PurgeInfo

### ISSUE THREAD

**Issue by Valodim** [aperezdc/synpurge#17] opened 2017-10-09 18:36 UTC
Getting this error when I try to run synpurge with any configuration:

```
Traceback (most recent call last):
  File "bin/synpurge", line 11, in <module>
    load_entry_point('synpurge==4', 'console_scripts', 'synpurge')()
  File "/home/valodim/synpurge/lib/python3.5/site-packages/argh/dispatching.py", line 370, in __call__
    return self._dispatch()
  File "/home/valodim/synpurge/lib/python3.5/site-packages/argh/dispatching.py", line 382, in _dispatch
    dispatch(parser)
  File "/home/valodim/synpurge/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/valodim/synpurge/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/valodim/synpurge/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/valodim/synpurge/lib/python3.5/site-packages/synpurge/cli.py", line 175, in purge
    purges = purger.resolve_room_ids(c, pgdb or api)
  File "/home/valodim/synpurge/lib/python3.5/site-packages/synpurge/purger.py", line 106, in resolve_room_ids
    return resolver.get_purge_info()
  File "/home/valodim/synpurge/lib/python3.5/site-packages/synpurge/purger.py", line 99, in get_purge_info
    return frozenset((info for room_id, info in self._rooms.items()))
TypeError: unhashable type: 'PurgeInfo'
```

**Comment by JaniM** [comment] 2017-12-11 09:08
Duplicate of #15 (which has way wrong title).

**Closed as completed** 2018-03-19 14:51 UTC
